import { ModelsEvent } from "../../../api/Api";

export const emptyEventList: ModelsEvent[] = [
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 1,
		latitude: 55.684758,
		longitude: 37.738521,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 2,
		latitude: 56.664458,
		longitude: 37.734521,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 3,
		latitude: 55.234758,
		longitude: 37.348921,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 4,
		latitude: 50.683478,
		longitude: 37.733451,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 5,
		latitude: 53.689758,
		longitude: 37.718521,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 6,
		latitude: 51.684722,
		longitude: 32.738501,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 7,
		latitude: 58.684758,
		longitude: 33.738321,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 8,
		latitude: 55.614758,
		longitude: 37.738355,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 9,
		latitude: 57.685658,
		longitude: 39.708521,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 10,
		latitude: 52.634758,
		longitude: 37.766571,
		name: "string",
	},
	{
		avatar: "string",
		club: {
			avatar: "string",
			description: "string",
			events_count: 3,
			id: 2,
			name: "string",
			participants_count: 3,
			tags: [],
		},
		description: "string",
		event_date: "22.03.2022",
		id: 11,
		latitude: 58.684758,
		longitude: 38.338521,
		name: "string",
	},
];
