name: Frontend Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps
        run: npm ci

      - name: Eslint
        run: npm run eslint

      - name: Stylelint
        run: npm run stylelint

      - name: Typescript
        run: npm run tscompile
